- name: Install Logstash
  apt:
    name: logstash
    state: present

- name: Install new Logstash configuration file
  template:
    src: ./logstash.yml.j2
    dest: /etc/logstash/logstash.yml
  notify:
    - restart logstash

- name: Enable the Logstash service
  systemd:
    name: logstash
    enabled: yes
