- name: Install Kibana packages
  apt:
    name: kibana
    state: present

- name: Install new Kibana configuration file
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
  notify:
    - restart kibana

- name: Enable the Kibana service
  systemd:
    name: kibana
    enabled: yes
