- name: restart elasticsearch
  systemd:
    name: elasticsearch
    state: restarted
  become: true

- name: restart logstash
  systemd:
    name: logstash
    state: restarted
  become: true

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
  become: true
